services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672" # UI mq

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"     # Web UI
      - "4318:4318"       # OTLP Receiver

  notification-service:
    build: 
      context: .
    ports:
      - "8080:8080"
