FROM golang:alpine AS builder
WORKDIR /app
COPY . .

# tidy
RUN go mod tidy
RUN go build -o main .

# Stage 2: Run (Alpine)
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .

# Port (Cart=8082, Product=8081, Gateway=8000)
EXPOSE 8082

CMD ["./main"]